### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by SkyStorage** [giteczek/Translated-for-Reeses-Sodium-Options#1]
Can add Korean translation?

**Comment by SkyStorage** [comment]
+ Can I contribute on Korean translation?

**Comment by giteczek** [comment]
Korean language is included in <a href=https://github.com/giteczek/Translated-for-Reeses-Sodium-Options/blob/main/assets/reeses-sodium-options/lang/ko_kr.json>/assets/reeses-sodium-options/lang/ko_kr.json</a>.

**Comment by SkyStorage** [comment]
I didn't see sry
